src/CSMWebServer/app/board/models.py
from app import db
from app.board import constants as BOARD

from app.user.models import User

class Board(db.Model):
	__tablename__ = 'tbl_board'
	id = db.Column(db.Integer, primary_key=True)
	#user_id = db.Column(db.Integer, ForeignKey('user.id'))
	#user = db.ForeignKey(User)
	title = db.Column(db.String(150))
	content = db.Column(db.Text)
	type = db.Column(db.SmallInteger)

	def __init__(self, title=None, content=None, type=None):
		self.title = title
		self.content = content
		self.type = type
	
	def getType(self):
		return BOARD.TYPE[self.type]

src/CSMWebServer/app/player/models.py
from app import db

class Player(db.Model):
    __tablename__ = 'tbl_player'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer)
    room_id = db.Column(db.Integer)

    def __init__(self, user_id=None, room_id=None):
        self.user_id = user_id
        self.room_id = room_id

src/CSMWebServer/app/room/models.py
from app import db
from app.room import constants as ROOM 

class Room(db.Model):
    __tablename__ = 'tbl_room'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100,collation='utf8_general_ci'))
    type = db.Column(db.Integer)

    def __init__(self, title=None, type=None):
        self.title = title
        self.type = type
    def getType():
        return ROOM.TYPE[self.type]

src/CSMWebServer/app/user/models.py
from app import db
from app.user import constants as USER

class User(db.Model):
	__tablename__ = 'tbl_user'
	id = db.Column(db.Integer, primary_key=True)
	nickname = db.Column(db.String(120,collation='utf8_general_ci'), unique=True)
	email = db.Column(db.String(120,collation='utf8_general_ci'), unique=True)
	password = db.Column(db.String(120,collation='utf8_general_ci'))
	play_count = db.Column(db.Integer, default=0)
	win_count = db.Column(db.Integer, default=0)
	lose_count = db.Column(db.Integer, default=0)
        kill_sum = db.Column(db.Integer, default=0)
	role = db.Column(db.SmallInteger, default=USER.USER)
	status = db.Column(db.SmallInteger, default=USER.INACTIVE)

	def __init__(self, nickname=None, email=None, password=None):
		self.nickname = nickname
		self.email = email
		self.password = password

	def getStatus(self):
		return USER.STATUS[self.status]

	def getRole(self):
		return USER.ROLE[self.role]

src/CSMWebServer/app/room/forms.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import TextField, SelectField
from wtforms.validators import Required

class CreateRoomForm(Form):
    title = TextField('Room Title', [Required()])
    type = SelectField('Room Type', coerce=int, choices=[(1,1),(2,2),(3,3)])

src/CSMWebServer/app/user/forms.py
from flask.ext.wtf import Form, RecaptchaField
from flask.ext.wtf.html5 import EmailField
from wtforms import TextField, PasswordField
from wtforms.validators import Required, EqualTo, Email

class LoginForm(Form):
	email = EmailField('Email address', [Required(), Email()])
	password = PasswordField('Password', [Required()])

class RegisterForm(Form):
	email = EmailField('Email address', [Required(), Email()])
	password = PasswordField('Password', [Required()])
	confirm = PasswordField('Repeat Pasword', [Required(), EqualTo('password', message='Passwords must match')])
	nickname = TextField('NickName', [Required()])

	#recaptcha = RecaptchaField()

src/CSMWebServer/app/__init__.py
from flask import Flask, render_template
from flask.ext.sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)

@app.errorhandler(404)
def not_found(error):
	return render_template('404.html'), 404

from app.user.views import mod as userModule
from app.general.views import mod as generalModule
from app.board.views import mod as boardModule
from app.room.views import mod as roomModule
from app.player.views import mod as playerModule
app.register_blueprint(userModule)
app.register_blueprint(generalModule)
app.register_blueprint(boardModule)
app.register_blueprint(roomModule)
app.register_blueprint(playerModule)

src/CSMWebServer/app/board/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for

from app import db
from app.board.models import Board

mod = Blueprint('board', __name__, url_prefix='/board/')

@mod.route('/list/', methods=['GET'])
def list():
	return render_template("board/list.html")

@mod.route('/detail/<board_id>', methods=['GET'])
def detail():
	return render_template("board/detail.html")

src/CSMWebServer/app/general/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for

from app import db
from app.user.forms import LoginForm
from app.user.forms import RegisterForm
from app.user.models import User

mod = Blueprint('general', __name__, url_prefix='/')

@mod.route('/')
def main():
        login_form = LoginForm(request.form)
        register_form = RegisterForm(request.form)
	return render_template('general/main.html', user=g.user, login_form=login_form, register_form=register_form)

@mod.before_request
def before_request():
	g.user = None
	if 'user_id' in session:
		g.user = User.query.get(session['user_id'])

src/CSMWebServer/app/player/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for

from app import db
from app.player.models import Player

mod = Blueprint('player',__name__,url_prefix='/player')

src/CSMWebServer/app/room/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for

from app import db
from app.room.forms import CreateRoomForm
from app.room.models import Room
from app.user.models import User
from app.player.models import Player
from app.user.decorators import requires_login

mod = Blueprint('room', __name__, url_prefix='/room')

@mod.route('/')
@requires_login
def room_list():
    game_list = Room.query.all()
    for game in game_list:
        game.player_count = Player.query.filter_by(room_id=game.id).count()

    user = Player.query.filter_by(user_id=session['user_id']).first()
    if user:
        return redirect(url_for("room.already"))

    return render_template("room/lobby.html", game_list=game_list, user_id=session['user_id'])

@mod.route('/create/', methods=['GET','POST'])
@requires_login
def room_create():
    form = CreateRoomForm(request.form)

    #if form.validate_on_submit():
    if request.method == 'POST' and form.title.data != None and form.type.data != None:
        room = Room(title=form.title.data, type=form.type.data)
        db.session.add(room)
        db.session.commit()

        return redirect(url_for("room.room_list"))
    
    return render_template("room/create_room.html")

@mod.route('/already/')
@requires_login
def already():
    user = Player.query.filter_by(user_id=session['user_id']).first()
    if not user:
        return redirect(url_for("room.room_list"))

    return render_template("room/already_game.html")

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

src/CSMWebServer/app/user/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.user.forms import RegisterForm, LoginForm
from app.user.models import User
from app.user.decorators import requires_login

mod = Blueprint('user', __name__, url_prefix='/user')

'''
@mod.route('/')
@requires_login
def profile():
	return render_template("user/profile.html", user=g.user)
'''
@mod.before_request
def before_request():
	g.user = None
	if 'user_id' in session:
		g.user = User.query.get(session['user_id'])

@mod.route('/login/', methods=['POST'])
def login():
	form = LoginForm(request.form)

	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()

		if user and check_password_hash(user.password, form.password.data):
			session['user_id'] = user.id
			flash('Welcome %s' % user.nickname)
			return redirect(url_for('general.main'))
		flash('Worng email or password', 'error-message')
	return redirect(url_for('general.main')) 

@mod.route('/register/', methods=['POST'])
def register():
	form = RegisterForm(request.form)
	if form.validate_on_submit():
		user = User(nickname=form.nickname.data, email=form.email.data, password=generate_password_hash(form.password.data))
		db.session.add(user)
		db.session.commit()

		session['user_id'] = user.id

		flash('Thanks for registering')

		return redirect(url_for('general.main'))
        return redirect(url_for('general.main'))

@mod.route('/logout/', methods=['GET'])
def logout():
	session.clear()
	g.user = None
	return redirect(url_for('general.main'))

src/CSMWebServer/app/templates/base.html
<!doctype html>
<html lang="ko">
	<head>
		<title>레전드 오브 리그 - 정령왕</title>
		<meta charset="utf-8" />
		<!-- FontAwesome CDN -->
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		<!-- Normalize CSS -->
		<link rel="stylesheet" href="/static/styles/normalize.css" />
		<!-- Common CSS -->
		<link rel="stylesheet" href="/static/styles/common.css?140106" />
        <!-- jQuery CDN -->
		<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>

		<link rel="stylesheet" type="type/css" href="/static/styles/common.css" />

		{% block styles %}
		{% endblock %}

		{% block scripts %}
		{% endblock %}
	</head>
	<body>
		<div class="bg"></div>

		<div class="gameTitle">레전드 오브 리그 <span>: 정령왕</span></div>

		{% block content %}
		{% endblock %}

		<div class='footer'>
			<a class='title'>레전드 오브 리그: 정령왕</a>
			<span class='creater'>CSM - 김지환, 남세현, 이선협, 장문익</span>
		</div>
	</body>
</html>

src/CSMWebServer/app/templates/forms/user/macros.html
{% macro render_field(field) %}
	<div class="form_field">
	{% if field.errors %}   
		{% set css_class = 'has_error ' + kwargs.pop('class', '') %}
		{{ field(class=css_class, **kwargs) }}
		<ul class="errors">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
	{% else %}
		{{ field(**kwargs) }}
	{% endif %}
	</div>
{% endmacro %}

src/CSMWebServer/app/templates/general/main.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" type="type/css" href="/static/styles/main.css?20140108" />
{% endblock %}

{% block scripts %}
<script src="/static/scripts/main.js"></script>
{% endblock %}

{% block content %}
<script type="text/javascript">
	function plugin0() {
		return document.getElementById('plugin0');
	}
	plugin = plugin0;
	function addEvent(obj, name, func) {
		if (obj.attachEvent) {
			obj.attachEvent("on"+name, func);
		} else {
			obj.addEventListener(name, func, false);
		}
	}

	isLoad = false;

	function pluginLoaded() {
		isLoad = true;
	}
	function gameStart() {
		if (isLoad == true ) {
			{% if user %}
			//plugin().testEvent();
			location.href = "{{url_for('room.room_list')}}";
			{% else %}
			alert('먼저 로그인 해주세요. :)');
			{% endif %}
		} else {
			alert('설치호 새로고침 혹은 브라우저를 재실행 해주세요.');
			location.href = ''; // 인스톨러 파일 링크
		}
	}
</script>

<object id="plugin0" type="application/x-csm" width="0" height="0" border="0">
	<param name="onload" value="pluginLoaded" />
</object>
		
<div class="mainNav">
	<div class="startBtn" onclick="javascript:gameStart();">
		Start!
	</div>
	<ul class="menuList">
		{% if not user %}
		<li id="login">로그인</li>
		<li id="regist">회원가입</li>
		{% else %}
		<li id="info">정보보기</li>
		<li id="logout">로그아웃</li>
		{% endif %}
	</ul>
</div>

<div class="loginModal">
	<div class="loginModalInner">
		<div class="exit"><i class="fa fa-times"></i></div>
		{% from "forms/user/macros.html" import render_field %}
		<form class="form formLogin" method="post" action="{{url_for('user.login')}}">
			<h2 class='formHeading'>어서오세요!</h2>
			{{ login_form.csrf_token }}
			{{ render_field(login_form.email, placeholder="로그인") }}
			{{ render_field(login_form.password, placeholder="비밀번호") }}
			<button class='loginBtn'>로그인</button>
			<!--<a href="{{ url_for('user.register') }}" class='registBtn'>회원가입</a>-->
		</form>
	</div>
</div>

<div class="registModal">
	<div class="registModal">
		<div class="exit"><i class="fa fa-times"></i></div>
		{% from "forms/user/macros.html" import render_field %}
		<form class="form formRegist" method="post" action="{{url_for('user.register')}}">
			<h2 class="formHeading">환영합니다!</h2>
			{{ register_form.csrf_token }}
			{{ render_field(register_form.email, placeholder="이메일") }}
			{{ render_field(register_form.password, placeholder="비밀번호") }}
			{{ render_field(register_form.confirm, placeholder="비밀번호 확인") }}
			{{ render_field(register_form.nickname, placeholder="당신의 이름") }}
			<button class='registBtn'>회원가입</button>
		</form>
	</div>
</div>

<div class="userInfoModal">
	<div class="userInfoModalInner">
		<div class="exit"><i class="fa fa-times"></i></div>
		<div>총 게임 수: {{user.play_count}}</div>
		<div>승리 수: {{user.win_count}}</div>
		<div>패배 수: {{user.lose_count}}</div>
		<div>누적 킬 수 : {{user.kill_sum}}</div>
	</div>
</div>
{% endblock %}

src/CSMWebServer/app/templates/general/main2.html
<!doctype html>
<html lang="ko">
	<head>
		<title>레전드 오브 리그 - 정령왕</title>
		<meta charset="utf-8" />
		<!-- FontAwesome CDN -->
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		<!-- Normalize CSS -->
		<link rel="stylesheet" href="/static/styles/normalize.css" />
		<!-- Common CSS -->
		<link rel="stylesheet" href="/static/styles/common.css?140106" />
        <!-- jQuery CDN -->
		<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>

		<link rel="stylesheet" type="type/css" href="/static/styles/common.css" />
		<link rel="stylesheet" type="type/css" href="/static/styles/main.css" />

		<script src="/static/scripts/main.js"></script>
	</head>
		<script type="text/javascript">
			function plugin0() {
				return document.getElementById('plugin0');
			}
			plugin = plugin0;
			function addEvent(obj, name, func) {
				if (obj.attachEvent) {
					obj.attachEvent("on"+name, func);
				} else {
					obj.addEventListener(name, func, false);
				}
			}

			isLoad = false;

			function pluginLoaded() {
				isLoad = true;
			}
			function gameStart() {
				if (isLoad == true ) {
					{% if user %}
					plugin().testEvent();
					{% else %}
					alert('먼저 로그인 해주세요. :)');
					{% endif %}
				} else {
					location.href = ''; // 인스톨러 파일 링크
				}
			}
		</script>
	<body>
		<object id="plugin0" type="application/x-csm" width="0" height="0" border="0">
			<param name="onload" value="pluginLoaded" />
		</object>
		
		<div class="bg"></div>

		<div class="gameTitle">레전드 오브 리그 <span>: 정령왕</span></div>

		<div class="mainNav">
			<div class="startBtn" onclick="javascript:gameStart();">
				Start!
			</div>
			<ul class="menuList">
				{% if not user %}
				<li id="login">로그인</li>
				<li id="regist">회원가입</li>
				{% else %}
				<li id="info">정보보기</li>
				<li id="logout">로그아웃</li>
				{% endif %}
			</ul>
		</div>

		<div class="loginModal">
			<div class="loginModalInner">
				<div class="exit"><i class="fa fa-times"></i></div>
				{% from "forms/user/macros.html" import render_field %}
				<form class="form formLogin" method="post" action="{{url_for('user.login')}}">
					<h2 class='formHeading'>어서오세요!</h2>
					{{ login_form.csrf_token }}
					{{ render_field(login_form.email, placeholder="로그인") }}
					{{ render_field(login_form.password, placeholder="비밀번호") }}
					<button class='loginBtn'>로그인</button>
					<!--<a href="{{ url_for('user.register') }}" class='registBtn'>회원가입</a>-->
				</form>
			</div>
		</div>

		<div class="registModal">
			<div class="registModal">
				<div class="exit"><i class="fa fa-times"></i></div>
				{% from "forms/user/macros.html" import render_field %}
				<form class="form formRegist" method="post" action="{{url_for('user.register')}}">
					<h2 class="formHeading">환영합니다!</h2>
					{{ register_form.csrf_token }}
					{{ render_field(register_form.email, placeholder="이메일") }}
					{{ render_field(register_form.password, placeholder="비밀번호") }}
					{{ render_field(register_form.confirm, placeholder="비밀번호 확인") }}
					{{ render_field(register_form.nickname, placeholder="당신의 이름") }}
					<button class='registBtn'>회원가입</button>
				</form>
			</div>
		</div>

		<div class="userInfoModal">
			<div class="userInfoModalInner">
				<div class="exit"><i class="fa fa-times"></i></div>
				<div>총 게임 수: {{user.play_count}}</div>
				<div>승리 수: {{user.win_count}}</div>
				<div>패배 수: {{user.lose_count}}</div>
			</div>
		</div>

		<div class='footer'>
			<a class='title'>레전드 오브 리그: 정령왕</a>
			<span class='creater'>CSM - 김지환, 남세현, 이선협, 장문익</span>
		</div>
	</body>
</html>

src/CSMWebServer/app/templates/room/already_game.html
{% extends "base.html" %}

{% block styles %}
<style>
	.alreadyGameStart {
		position: fixed;
		left: 50%;
		top: 50%;
		width: 350px;
		height: 50px;
		margin-left: -175px;
		margin-top: -25px;
		line-height: 50px;
		text-align: center;
		font-size: 18pt;
		font-family: 'Nanum Gothic', sans-serif;
		font-weight: bold;
		color: white;
		z-index: 2;
		border-radius: 10px;
		background-color: #333;
	}
</style>
{% endblock %}

{% block scripts %}
<meta http-equiv="Refresh" content="3; URL=/room/already/ " />
{% endblock %}

{% block content %}
<div class='alreadyGameStart'>
	이미 게임을 시작하셨습니다!
</div>
{% endblock %}

src/CSMWebServer/app/templates/room/create_room.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="/static/styles/main.css?20140108" />
<link rel="stylesheet" type="text/css" href="/static/styles/create_room.css?20140108" />
{% endblock %}

{% block scripts %}
{% endblock %}

{% block content %}
<div class="createRoom">
	<div class="createRoomInner">
		<a href="{{url_for('room.room_list')}}" style="color:black;" class="exit"><i class="fa fa-times"></i></a>
		<h1 class="createRoomTitle">방 만들기</div>
		<form class="form formCreateRoom" method="post" action=".">
			<input type="text" name="title" placeholder="방제목" />
			<select name="type">
				<option>게임 방식</option>
				<option value='0'>4대4 데스매치</option>
				<!--<option value='1'>8대8 데스매치</option>
				<option value='2'>8대8 깃발뺏기</option>-->
			</select>
			<input type="submit" value="만들기" />
		</form>
	</div>
</div>
{% endblock %}

src/CSMWebServer/app/templates/room/lobby.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="/static/styles/main.css?20140108" />
<link rel="stylesheet" type="text/css" href="/static/styles/lobby.css?20140108" />
{% endblock %}

{% block scripts %}
{% endblock %}

{% block content %}
<script type="text/javascript">
function plugin0()
{
	return document.getElementById('plugin0');
}
plugin = plugin0;
function addEvent(obj, name, func) {
	if (obj.attachEvent) {
		obj.attachEvent("on"+name, func);
	} else {
		obj.addEventListener(name, func, false);
	}
}
isLoad = false;
function pluginLoaded() {
	isLoad = true;
}
function gameStart(roomId, userId) {
	if (isLoad == true ) {
		plugin().startGame(roomId,userId);
	} else {
		alert('게임 설치가 제대로 안된 것 같습니다..');
		location.href = ''; // 인스톨러 파일 링크
	}
}
</script>
<object id="plugin0" type="application/x-csm" width="0" height="0" border="0">
	<param name="onload" value="pluginLoaded" />
</object>
<div class="lobby">
	<div class="lobbyInner">
		<a href="{{url_for('general.main')}}" style='color:black' class="exit"><i class="fa fa-times"></i></a>
		<div class="lobbyHeader">
			<h1 class="lobbyTitle">레전도 오브 리그</h1>
			<a href="{{url_for('room.room_create')}}" class="createRoomBtn">새로운 게임 만들기</a>
		</div>
		<div class="lobbyContent">
			<div class="lobbyContentHeader">
				<div class="headerId">방번호</div>
				<div class="headerTitle">제목</div>
				<div class="headerType">경기형식</div>
				<div class="headerCount">인원수</div>
			</div>
			<ul class="roomList">
				{% for game in game_list %}
				<li class="room">
					<div class="id">{{game.id}}</div>
					<div class="title" onclick='javascript:gameStart({{game.id}},{{user_id}})'>{{game.title}}</div>
					<div class="type">
						{% if game.type == 0 %}
						4대4 데스매치
						{% elif game.type == 1 %}
						8대8 데스매치
						{% elif game.type == 2 %}
						8대8 깃발뺏기
						{% endif %}
					</div>
					<div class="count">
						{{game.player_count}}명 /
						{% if game.type == 0 %}
						4명
						{% elif game.type == 1 %}
						8명
						{% elif game.type == 2 %}
						8명
						{% endif %}
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
{% endblock %}

src/CSMWebServer/app/templates/user/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block styles %}
<link rel='stylesheet' href='/static/styles/login.css' />
{% endblock %}

{% block content %}
	<div class='container' style='padding-top: 40px;'>
		{% from "forms/user/macros.html" import render_field %}
		<form method="POST" action="." class="form-login" role='form'>
			<h2 class='form-login-heading'>Please Login</h2>
			{{ form.csrf_token }}
			{{ render_field(form.email, placeholder="로그인", class="form-control") }}
			{{ render_field(form.password, placeholder="비밀번호", class="form-control") }}
			<label class='checkbox'>
				<input type='checkbox' value='remember-me'> 아이디 저장
			</label>
			<button class='btn btn-lg btn-primary btn-block' type='submit'>Login</button>
			<a href="{{ url_for('user.register') }}" class='btn btn-lg btn-info btn-block'>회원가입</a>
		</form>
	</div>
{% endblock %}

src/CSMWebServer/app/templates/user/profile.html
{% extends "base.html" %}

{% block title %}
{{user.nickname}}'s Profile
{% endblock %}

{% block content %}
<div class='jumbotron'>
	<div class='container'>
		<h1>Hello, {{ user.nickname }}!</h1>
		<p>
			Your Email {{ user.email }} <br />
			Your Password {{ user.password }} <br />
			Your Role {{ user.getRole() }} <br />
			Your Status {{ user.getStatus() }} <br />
		</p>
		<p><a class='btn btn-primary btn-lg' role='button'>Go to lobby &raquo;</a></p>
	</div>
</div>
{% endblock %}

src/CSMWebServer/app/templates/user/register.html
{% extends "base.html" %}
{% block title %} Register {% endblock %}

{% block styles %}
<link rel='stylesheet' href='/static/styles/register.css' />
{% endblock %}

{% block content %}
	<div class='container' style='padding-top: 40px;'>
		{% from "forms/user/macros.html" import render_field %}
		<form method="POST" action="." class="form-register">
			<h2>Plaese Register</h2>
			{{ form.csrf_token }}
			{{ render_field(form.email, placeholder="이메일", class='form-control') }}
			{{ render_field(form.password, placeholder="비밀번호", class='form-control') }}
			{{ render_field(form.confirm, placeholder="비밀번호 확인", class='form-control') }}
			{{ render_field(form.nickname, placeholder="닉네임", class='form-control') }}
			<p><strong>자동가입 방지</strong></p>
			{{ form.recaptcha }}
			<button class='btn btn-lg btn-info btn-block' type='submit'>회원가입</button>
			<a href='{{ url_for('user.login') }}' class='btn btn-lg btn-primary btn-block'>로그인</a>
		</form>
	</div>
{% endblock %}